### ISSUE TITLE
Error when Title contains UTF8 Text

### ISSUE THREAD

**Issue by chforster** [chforster/python_tutorial#2]
When the Title of e.g. an Attachment contains a UTF-8 encoded Text the export will fail with the following error message:

```
Traceback (most recent call last):
  File "./grabConfluence.py", line 93, in <module>
    writeChildren(rootId, directory)
  File "./grabConfluence.py", line 66, in writeChildren
    writeChildren(childid, parent)
  File "./grabConfluence.py", line 66, in writeChildren
    writeChildren(childid, parent)
  File "./grabConfluence.py", line 66, in writeChildren
    writeChildren(childid, parent)
  File "./grabConfluence.py", line 66, in writeChildren
    writeChildren(childid, parent)
  File "./grabConfluence.py", line 71, in writeChildren
    print("\tWrite {}Attachment{} {} in directory {}".format(bcolors.BOLD, bcolors.ENDC, bcolors.OKBLUE + attachment['title'] + bcolors.ENDC, directory))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 34: ordinal not in range(128)

```

**Comment by chforster** [comment]
Fixed with commit 69bda3a
